### ISSUE TITLE
请问如何使用fcitx-rime

### ISSUE THREAD

**Issue by scinart** [fcitx/fcitx-rime#24]
原来一直用fcitx码表输入，现在我用Ubuntu的apt-get安装了`fcitx-rime`, `librime-data-wubi`(及其很多依赖)之后，重启fcitx，fcitx和原来没有变化，在fcitx的设置里找了一圈也没找到 **rime** 的影子，请告诉我如何设置啊？谢谢啦。

**Comment by iugo** [comment]
我 Ubuntu 14.04 重啓後就可以找到 Rime 了.

**Comment by scinart** [comment]
补充：我已经不用Ubuntu了
