### ISSUE TITLE
中州韵在Fedora下默认安装之后在右键的输入法里找不到，必须手动添加

### ISSUE THREAD

**Issue by neilgen** [fcitx/fcitx-rime#33]
测试fedora25有这个问题。自己在fedora21上编译的版本也存在这个问题

**Comment by SmallFatCYW** [comment]
+1，我在Ubuntu1604上安装搜狗输入法时也是要手动添加。。。并且deb安装时还报了错，害我以为没成功。。。但是其实成功了。。。

**Comment by wengxt** [comment]
not a bug.
