### ISSUE TITLE
the emoji does not work

### ISSUE THREAD

**Issue by braindevices** [fcitx/fcitx-rime#34]
it can only output boxes instead of the utf8 emoji. For example: ☀, ☔

**Comment by yuyichao** [comment]
![spectacle zti570](https://cloud.githubusercontent.com/assets/712232/25309997/81e5f954-27a8-11e7-95ee-f7d5181d7c89.png)

You need to use a font that supports those unicode characters.

**Comment by yuyichao** [comment]
And if you need help finding one. https://wiki.archlinux.org/index.php/fonts#Emoji_and_symbols (Google should also help as usual).

**Comment by wengxt** [comment]
Most likely, it's a font problem. Try to see if install ttf-noto-emoji helps.
It could be a bug in the application. I used to fix one related bug in kate.

**Comment by braindevices** [comment]
@yuyichao @wengxt Thanks a lot! I fixed it by installing ttf-noto fonts.
