### ISSUE TITLE
進行“重新部署”或“同步”時fcitx崩潰

### ISSUE THREAD

**Issue by renyuneyun** [fcitx/fcitx-rime#35]
前一段改了rime的一個自定義詞庫，需要重新部署。然而當點擊重新部署時，rime的提示出現，然後/同時fcitx崩潰，而且rime的重新部署也沒有完成。
另不小心點到了“同步”（然而我沒有配置過同步相關設置），fcitx也會崩潰。

之間沒有動過fcitx的配置，rime的其他配置也沒有改過（除了那一個詞典）。

環境：
* archlinux x86_64 
* fcitx 4.2.9.1-2
* fcitx-rime 0.3.1-3
* librime 1:1.2.9-4

fcitx從啓動到崩潰的stderr：
[fcitx.txt](https://github.com/fcitx/fcitx-rime/files/1012339/fcitx.txt)

**Comment by chih7** [comment]
我这里 leveldb 升级到1.20后 rime 同步时 fcitx 崩溃，把 leveldb 降级到1.19就好了。

**Comment by renyuneyun** [comment]
現在好了，不確定具體是什麼時候好的。
但至少leveldb還是1.20，所以應該是rime或者fcitx哪裏改了。

**Comment by hosiet** [comment]
Debian 下游报告： https://bugs.debian.org/883373

如果你的系统上出现同样的问题，考虑重新构建一次 librime。
