### ISSUE TITLE
可疑的上屏bug

### ISSUE THREAD

**Issue by ellicefix** [fcitx/fcitx-rime#39]
之前，fcitx-rime 有一个上屏bug，我曾觉得那可能是 librime 的问题，情形如下：

[在这份码表里](http://t.cn/RQtG8dV)，ALL 是「空码」，但 ALL后续的编码其实还有字：

蘲	allf	18880
虆	alli	18879
藟	alll	18878
蘽	alls	18877

如果我想打出 ALLS 或 ALLF，都是不可能的，

因为，fcitx-rime 会把 AL 字段对应的 「苗」字，给送上屏去。

大概是它在检索到 ALL 时，发现是「空码」，便不再接收新的输入事件，径直把「前2码」能对应的「苗」字顶上屏去了。

日前，我编译了 fcitx & fcitx-rime & librime & brise ,但我发现，不论是选用哪个版本的 librime ，都会复现这个问题。

而在中州韵别的前端，比如 android 上的 trime，MacOS 上的 鼠须管，Win10上的 Prime，在编译时，选用较新的 librime 分支，都已经修复了这个问题。

码表，是比较典型的五笔码表，配置文件是在所有平台都正常工作的配置文件。您放到~/.config/fcitx/rime 下，重新部署就会生效。

请您查证一下，非常感谢。

**Comment by ellicefix** [comment]
不知您是否还会看到这里……

**Comment by ellicefix** [comment]
大大，录屏：

https://goo.gl/KAC3Yq

**Comment by wengxt** [comment]
安装 master 的 librime 之后测试没有问题。你编译 fcitx-rime 是否使用了你新编译的 librime？
